### ISSUE TITLE
Visual Studio 2019 Squash Commits via a GUI 👏👏

### ISSUE THREAD

**Issue by spottedmahn** [spottedmahn/my-blog#26]
Reference: [Dev Community: Squash commits in Git using Visual Studio](https://developercommunity.visualstudio.com/idea/351072/squash-commits-in-git-using-visual-studio.html?childToView=596582)

![image](https://user-images.githubusercontent.com/14079228/59038114-7f81ac80-8840-11e9-9f78-91ba288a92a6.png)

![image](https://user-images.githubusercontent.com/14079228/59038125-827c9d00-8840-11e9-947c-b29fe7363af6.png)

![image](https://user-images.githubusercontent.com/14079228/59038135-84def700-8840-11e9-86b3-cabb09703c2a.png)

## Warning

Hitting enter on the Squash Commits dialog **does not** add a line but triggers the Squash button 😱

**Comment by corradocavalli** [comment]
Why the menu is disabled in local branches? I see it enabled on remote branches but looks like the commit aren't squashed.
Am I missing something?

**Comment by spottedmahn** [comment]
>Why the menu is disabled in local branches?

Not for me.  🤔

![image](https://user-images.githubusercontent.com/14079228/72175295-da1c5180-33a9-11ea-9290-a18065ad4a28.png)

>I see it enabled on remote branches but looks like the commit aren't squashed.

That seems backward.  Surprised this works:

![image](https://user-images.githubusercontent.com/14079228/72175461-35e6da80-33aa-11ea-9d98-a3f3e520a344.png)

Well, actually **it doesn't**.  The menu items should be displayed for remote only branches it would seem:

![image](https://user-images.githubusercontent.com/14079228/72175577-7181a480-33aa-11ea-9e2c-fb51ee85b79d.png)

**Comment by corradocavalli** [comment]
The reason of disabled Squash commits menu was a mistake on my side, but honestly is still unclear how this feature work.
My goal is to squash all commits inside a branch into a new one, of course this commits can be pushed to remote branch in different steps, so on remote, at some point, i can have these commits to be squashed: commit1, commit 2 and commit3.
If i squash commits on local branch when i try to push the squashed ones i have an error because there are some changes i need to pull first (think this i because of rebasing behind the squash commit operation)
If i do the same on remote branch, looks like nothing happen on it, but if i then view local branch history i see the squashed commit there, but if i then try to push the local branch is see the same squashed commits requiring to be pulled first.
What is the correct way to use this Squash feature with the plugin? 🙄

**Comment by spottedmahn** [comment]
>If i squash commits on local branch when i try to push the squashed ones i have an error because there are some changes i need to pull first (think this i because of rebasing behind the squash commit operation)

Sounds like you'll need to `--force` push in that case

![image](https://user-images.githubusercontent.com/14079228/72186548-8a4a8400-33c3-11ea-812a-ce485181aad7.png)

I toggle that back off after I need to use it.

**Comment by corradocavalli** [comment]
Thanks, it worked, but is this supposed to work this way? after all i think is quite normal, especially when you completed a feature branch to squash commits before submitting a PR...

**Comment by spottedmahn** [comment]
>Thanks, it worked

🥳😀

>but is this supposed to work this way?

Yes, I believe so.  [A squash](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) is really a rebase and:

>[No one shall rebase a shared branch](https://www.daolf.com/posts/git-series-part-2/)

While you're only sharing the branch w/ yourself, I assume, it is shared w/ the remote.

And a rebase:
>it’s literally rewriting your project history  [source](https://hackernoon.com/mastering-git-why-rebase-is-amazing-a954485b128a)

**Comment by spottedmahn** [comment]
>after all i think is quite normal, especially when you completed a feature branch to squash commits before submitting a PR...

Do you use Azure DevOps?  [It can squash them](https://docs.microsoft.com/en-us/azure/devops/repos/git/merging-with-squash?view=azure-devops) for you so you don't have to 😀

**Comment by corradocavalli** [comment]
I know, but unfortunately we dont...
